spring.application.name=app

#this is a trump card to show every actualtor endpoint without any restrictions
management.endpoints.web.exposure.include = *
management.endpoints.web.exposure.exclude = info
management.info.env.enabled=true

info.app.name = My first app
info.app.description = The cool app is my first try , lol 
info.app.version = 1.0.0

spring.security.user.name = roshan
spring.security.user.password = yadav
